### ISSUE TITLE
Can't convert np.ndarray of type numpy.int32

### ISSUE THREAD

**Issue by RamyaRaghuraman** [junbaoZHUO/UODTN#1]
Hi all,

I get the following error when I run the script train_gcn_basic_awa_ezhuo_2019.py

`using gpu 0
C:/Users/RAR7ABT/pj-val-ml/pjval_ml/OSR/UODTN/GCN/train_gcn_basic_awa_ezhuo_2019.py:67: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  fc_vectors = torch.tensor(fc_vectors).cuda()
Traceback (most recent call last):
  File "C:/Users/RAR7ABT/pj-val-ml/pjval_ml/OSR/UODTN/GCN/train_gcn_basic_awa_ezhuo_2019.py", line 76, in <module>
    gcn = GCN(n, edges, word_vectors.shape[1], fc_vectors.shape[1], hidden_layers).cuda()
  File "C:\Users\RAR7ABT\pj-val-ml\pjval_ml\OSR\UODTN\GCN\models\gcn.py", line 52, in __init__
    adj = spm_to_tensor(adj)
  File "C:\Users\RAR7ABT\pj-val-ml\pjval_ml\OSR\UODTN\GCN\utils.py", line 68, in spm_to_tensor
    (sparse_mx.row, sparse_mx.col))).long()
TypeError: can't convert np.ndarray of type numpy.int32. The only supported types are: double, float, float16, int64, int32, and uint8.

Process finished with exit code 1`

Any help would be appreciated. Thank you!

**Comment by junbaoZHUO** [comment]
what is the pytorch version?

**Comment by RamyaRaghuraman** [comment]
Python 3.6.8
conda 4.4.11
pytorch 1.0.1

**Comment by junbaoZHUO** [comment]
how about the version of numpy?  try numpy 1.15+.

**Comment by RamyaRaghuraman** [comment]
I am using numpy version 1.17

**Comment by RamyaRaghuraman** [comment]
@junbaoZHUO I think there is a formatting error while loading the "151+16_cls_from_1K_ft" file in the script "train_gcn_basic_awa_ezhuo_2019.py". Could you please tell me the format of the file "151+16_cls_from_1K_ft", because currently the file is being loaded in UTF-8 format for me.

**Comment by junbaoZHUO** [comment]
It is generated from train_40_cls_with_help_of_1K.py. So I don't know the format.

**Comment by junbaoZHUO** [comment]
We can not reproduce the error. We use the gcn lib provided in https://github.com/cyvius96/DGP, which requires pytorch 0.4. Run some code https://github.com/cyvius96/DGP perhaps help to validate your environment.

**Comment by RamyaRaghuraman** [comment]
@junbaoZHUO I followed the steps in https://github.com/cyvius96/DGP but ended up with the exact error when I tried to run train_gcn_basic.py.  I ran this in a new conda environment with the following dependencies:

Python 3.6.8
conda 4.4.11
pytorch 0.4.0
numpy 1.17
nltk 3.4.4

**Comment by junbaoZHUO** [comment]
does https://discuss.pytorch.org/t/cant-convert-a-given-np-ndarray-to-a-tensor/21321/2 or https://stackoverflow.com/questions/55724123/typeerror-cant-convert-np-ndarray-of-type-numpy-object help? Can you print the sparse_mx.row via print(sparse_mx.row)?

**Comment by RamyaRaghuraman** [comment]
The following is the output for sparse_mx.row and sparse_mx.col:

`row [  0   0   1   1   2   2   3   3   4   4   5   5   6   6   7   7   8   8
   9   9  10  10  11  11  12  12  13  13  14  14  15  15  16  16  17  17
  18  18  19  19  20  20  21  21  22  22  23  23  24  24  25  25  26  26
  27  27  28  28  29  29  30  30  31  31  32  32  33  33  34  34  35  35
  36  36  37  37  38  38  39  39  40  40  41  41  42  42  43  43  44  44
  45  45  46  46  47  47  48  48  49  49  50  50  51  51  52  52  53  53
  54  54  55  55  56  56  57  57  58  58  59  59  60  60  61  61  62  62
  63  63  64  64  65  65  66  66  67  67  68  68  69  69  70  70  71  71
  72  72  73  73  74  74  75  75  76  76  77  77  78  78  79  79  80  80
  81  81  82  82  83  83  84  84  85  85  86  86  87  87  88  88  89  89
  90  90  91  91  92  92  93  93  94  94  95  95  96  96  97  97  98  98
  99  99 100 100 101 101 102 102 103 103 104 104 105 105 106 106 107 107
 108 108 109 109 110 110 111 111 112 112 113 113 114 114 115 115 116 116
 117 117 118 118 119 119 120 120 121 121 122 122 123 123 124 124 124 125
 125 125 126 126 126 127 127 128 128 129 129 130 130 131 131 132 132 133
 133 134 134 135 135 136 136 137 137 138 138 139 139 140 140 141 141 142
 142 143 143 144 144 145 145 146 146 147 147 148 148 149 149 150 150 151
 151 152 152 152 152 152 153 153 153 153 153 153 154 154 155 155 155 155
 156 156 156 156 156 156 157 157 158 158 159 159 159 160 160 161 161 162
 162 162 162 162 163 163 164 164 165 165 166 166 167 167 167 168 168 168
 169 169 170 170 171 171 172 172 173 173 173 174 174 175 175 176 176 177
 177 177 177 178 178 178 178 179 179 179 179 179 180 180 180 181 181 181
 181 181 181 181 181 181 182 182 182 183 183 183 184 184 184 184 185 185
 185 185 186 186 186 186 186 186 186 186 186 186 186 186 186 187 187 187
 187 187 187 188 188 188 188 188 188 188 188 188 188 188 188 188 189 189
 189 190 190 190 191 191 191 191 192 192 192 192 192 192 192 192 192 192
 192 192 192 192 192 192 192 193 193 193 193 193 193 194 194 194 195 195
 195 195 196 196 196 196 196 197 197 197 197 197 198 198 198 198 198 198
 198 199 199 199 199 199 199 199 199 200 200 200 200 201 201 201 201 201
 201 201 201 202 202 202 202 202 202 203 203 203 203 204 204 204 204 205
 205 205 205 205 205 205 205 205 205 206 206 206 207 207 207 207 207 208
 208 208 209 209 209 210 210 210 210 210 210 210 211 211 211 211 211 211
 211 211 211 212 212 212 213 213 213 213 213 214 214 214 214 215 215 215
 215 215 215 215 215 215 216 216 216 216 216 216 216 216 217 217 217 217
 218 218 218 218 218 219 219 219 220 220 220 220 220 220 220 220 221 221
 221 221 221 221 221 222 222 222 222 223 223 223 223 224 224 224 225 225
 225 226 226 226 227 227 227 227 227 228 228 228 228 229 229 229 230 230
 230 230 230 230 230 230 230 230 230 230 230 231 231 231 231 232 232 232
 232 233 233 233 233 234 234 234 234 234 235 235 235 235 236 236 236 236
 236 236 236 236 237 237 237 237 238 238 238 238 239 239 239 240 240 240
 240 241 241 241 241 242 242 242 242 243 243 243 243 243 244 244 244 244
 245 245 245 245 246 246 246 247 247 247 248 248 248 249 249 249 249 250
 250 250 251 251 251 252 252 252 253 253 254 254 254]
col [177   0 177   1 178   2 179   3 180   4 181   5 181   6 181   7 181   8
 182   9 181  10 183  11 184  12 184  13 185  14 185  15 186  16 186  17
 186  18 186  19 186  20 186  21 186  22 186  23 187  24 187  25 187  26
 187  27 188  28 188  29 189  30 190  31 188  32 188  33 188  34 191  35
 191  36 192  37 192  38 192  39 192  40 192  41 193  42 193  43 193  44
 193  45 194  46 195  47 195  48 196  49 196  50 196  51 192  52 156  53
 156  54 156  55 156  56 197  57 197  58 197  59 198  60 153  61 153  62
 153  63 153  64 199  65 199  66 199  67 200  68 201  69 201  70 201  71
 202  72 202  73 203  74 203  75 155  76 204  77 155  78 205  79 205  80
 206  81 173  82 207  83 207  84 208  85 167  86 162  87 162  88 162  89
 209  90 210  91 211  92 211  93 211  94 211  95 212  96 213  97 214  98
 214  99 215 100 215 101 215 102 215 103 215 104 215 105 215 106 216 107
 216 108 216 109 216 110 216 111 217 112 217 113 152 114 152 115 218 116
 219 117 220 118 220 119 220 120 220 121 220 122 220 123 221 157 124 202
 163 125 200 176 126 168 127 205 128 192 129 199 130 186 131 199 132 211
 133 201 134 210 135 201 136 216 137 213 138 222 139 213 140 205 141 181
 142 211 143 211 144 223 145 218 146 207 147 201 148 202 149 186 150 224
 151 226 225 152 115 114 198 153  64  63  62  61 205 154 204 155  78  76
 198 156  56  55  54  53 157 124 222 158 227 166 159 205 160 179 161 221
 162  89  88  87 163 125 228 164 218 165 166 159 221 167  86 229 168 127
 230 169 231 170 179 171 205 172 223 173  82 231 174 227 175 176 126 232
 177   1   0 232 230 178   2 233 179 171 161   3 234 180   4 192 182 181
 142  10   8   7   6   5 182 181   9 192 183  11 188 184  13  12 186 185
  15  14 188 186 185 150 131  23  22  21  20  19  18  17  16 188 187  27
  26  25  24 192 191 190 189 188 187 186 184  34  33  32  29  28 189 188
  30 190 188  31 191 188  36  35 235 198 196 195 194 193 192 188 183 181
 129  52  41  40  39  38  37 193 192  45  44  43  42 194 192  46 195 192
  48  47 196 192  51  50  49 198 197  59  58  57 236 198 197 192 156 153
  60 237 235 199 132 130  67  66  65 237 200 126  68 238 201 148 136 134
  71  70  69 236 202 149 125  73  72 236 203  75  74 239 204 155  77 230
 206 205 172 160 154 141 128  80  79 206 205  81 210 207 147  84  83 221
 208  85 210 209  90 240 227 210 209 207 135  91 236 211 144 143 133  95
  94  93  92 230 212  96 241 213 140 138  97 241 214  99  98 242 215 106
 105 104 103 102 101 100 242 216 137 111 110 109 108 107 243 217 113 112
 236 218 165 146 116 244 219 117 245 220 123 122 121 120 119 118 246 227
 221 208 167 162 124 246 222 158 139 228 223 173 145 230 224 151 230 225
 152 230 226 152 227 221 210 175 159 240 228 223 164 233 229 168 243 240
 239 236 234 230 226 225 224 212 205 178 169 234 231 174 170 247 232 178
 177 248 233 229 179 248 234 231 230 180 249 235 199 192 238 236 230 218
 211 203 202 198 238 237 200 199 238 237 236 201 239 230 204 240 230 228
 210 250 241 214 213 243 242 216 215 250 243 242 230 217 254 251 244 219
 252 249 245 220 246 222 221 249 247 232 248 234 233 249 247 245 235 250
 243 241 253 251 244 254 252 245 253 251 254 252 244]`

The datatype of sparse_mx is float32 and np.vstack((sparse_mx.row, sparse_mx.col)) is int32.

**Comment by junbaoZHUO** [comment]
Try to replace https://github.com/junbaoZHUO/UODTN/blob/aa46d3971f0e96fbc299225d8db3052da9db006f/GCN/utils.py#L67-L68 with indices = torch.from_numpy(np.vstack(
            (sparse_mx.row, sparse_mx.col)).astype(np.int32)).long()

**Comment by RamyaRaghuraman** [comment]
yup just did it this way:

temp = np.vstack((sparse_mx.row, sparse_mx.col)).astype(np.float32)
    indices = torch.from_numpy(temp).long()

works now! Thank you!

**Comment by junbaoZHUO** [comment]
great!

**Comment by RamyaRaghuraman** [comment]
in extract_feature.py, in line 14 do you mean model_path ='resnet50-raw.pth'? I get the following error:
` File "C:/Users/RAR7ABT/pj-val-ml/pjval_ml/OSR/UODTN/data/Matching/extract_feature.py", line 17, in <module>
    cnn.load_state_dict(torch.load(model_path))
  File "C:\Users\RAR7ABT\AppData\Local\conda\conda\envs\test\lib\site-packages\torch\nn\modules\module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ResNetBase:
	Unexpected key(s) in state_dict: "fc.weight", "fc.bias". `

I guess fc.weight and fc.bias must be popped as in https://github.com/cyvius96/DGP/blob/master/materials/process_resnet.py?

**Comment by junbaoZHUO** [comment]
No, it contains only convolutional layers.  Just run https://github.com/cyvius96/DGP/blob/master/materials/process_resnet.py? to get resnet50-base.pth.

**Comment by RamyaRaghuraman** [comment]
Yup works fine now! Also the cat command in line 9 in match_5_split.py does not work in a windows machine. So I have used the following:

filenames = ['file1.txt', 'file2.txt', ...]
with open('path/to/output/file', 'w') as outfile:
    for fname in filenames:
        with open(fname) as infile:
            for line in infile:
                outfile.write(line)
