### ISSUE TITLE
base_net_pretrained_on_I2AwA2_source_only.pkl file is not generated

### ISSUE THREAD

**Issue by RamyaRaghuraman** [junbaoZHUO/UODTN#2]
@junbaoZHUO 
In step 3, the "base_net_pretrained_on_I2AwA2_source_only.pkl" file is not generated from "train_40_cls_with_help_of_1K.py". This file is also being used in line 186 of train_UODTN.py. I am not sure if i am missing out anything. Could you please help with this issue? Thank you!

**Comment by junbaoZHUO** [comment]
Sorry for the mistake, you can rename the weights generated by https://github.com/junbaoZHUO/UODTN/blob/aa46d3971f0e96fbc299225d8db3052da9db006f/train_40_cls_with_help_of_1K.py#L95 into base_net_pretrained_on_I2AwA2_source_only.pkl.
